name: Coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lcov libgl1-mesa-dev xorg-dev

            - name: Configure CMake
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DMVN_DS_BUILD_TESTS=ON -DCMAKE_C_FLAGS="--coverage"

            - name: Build
              run: cmake --build ${{github.workspace}}/build

            - name: Run tests
              working-directory: ${{github.workspace}}/build
              run: ctest --output-on-failure

            - name: Generate coverage report
              run: |
                  lcov --capture --directory ${{github.workspace}}/build --output-file coverage.info
                  lcov --remove coverage.info '*/_deps/*' --output-file coverage.info
                  lcov --remove coverage.info '*/tests/*' --output-file coverage.info
                  lcov --list coverage.info

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: ./coverage.info
